spring:
  datasource:
    url: jdbc:mysql://localhost:3306/workBase
    username: root
    password: MySqlCode123
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create